language: bash

services:
  - docker

script:
  # Build the deb package in the yarn development container
  - docker run -u $(id -u):$(id -g) -v $PWD:$PWD -w $PWD yarnpkg/dev:latest /bin/sh -c "yarn && yarn build-dist && scripts/build-deb.sh"

  # Install gcloud so we can upload the build to our bucket
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version

  # Authenticate
  - echo $GOOGLE_CREDENTIALS_BASE64 | base64 -d > credentials.json
  - gcloud auth activate-service-account --key-file=credentials.json

  # Upload the built snap file
  - sudo gsutil cp artifacts/*.deb $GOOGLE_BUCKET/stemn-yarn-$TRAVIS_BRANCH.deb
