language: bash

script:
  # Install gcloud so we can upload the build to our bucket
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version

  # Authenticate
  - echo $GOOGLE_CREDENTIALS_BASE64 > base64.json
  - base64 -d base64.json > credentials.json
  - gcloud auth activate-service-account --key-file=credentials.json

  # Upload the built snap file
  - mv artifacts/*.deb stemn-yarn.deb
  - gsutil cp stemn-yarn.deb $GOOGLE_BUCKET
